name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "src/**", "test/**", "SharpLzo.sln" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "src/**", "test/**", "SharpLzo.sln" ]
  workflow_dispatch:

env:
  LZO_VERSION: "2.10"

jobs:
  compile-lzo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {target: windows-static-x86, src: liblzo2.dll, dst: liblzo2.dll, rid: win-x86}
          - {target: windows-static-x64, src: liblzo2.dll, dst: liblzo2.dll, rid: win-x64}
          - {target: linux-x64, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-x64}
          - {target: linux-armv6, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-arm}
          - {target: linux-arm64, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-arm64}
          - {target: web-wasm, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - run: | 
        wget https://www.oberhumer.com/opensource/lzo/download/lzo-${{ env.LZO_VERSION }}.tar.gz
        tar -xzvf lzo-${{ env.LZO_VERSION }}.tar.gz
        cmake -B build/$target -S src/lzo/ -G Ninja -DENABLE_STATIC=0 -DENABLE_SHARED=1
        ninja -C build/$target lzo_shared_lib