name: CI

on:
  push:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "src/**", "test/**", "SharpLzo.sln" ]
  pull_request:
    branches: [ "main", "dev" ]
    paths: [ ".github/workflows/ci.yml", "src/**", "test/**", "SharpLzo.sln" ]
  workflow_dispatch:

env:
  LZO_VERSION: "2.10"

jobs:
  compile-lzo:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler:
          - {target: windows-static-x86, src: liblzo2.dll, dst: liblzo2.dll, rid: win-x86}
          - {target: windows-static-x64, src: liblzo2.dll, dst: liblzo2.dll, rid: win-x64}
          - {target: linux-x64, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-x64}
          - {target: linux-armv6, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-arm}
          - {target: linux-arm64, src: liblzo2.so.2.0.0, dst: liblzo2.so, rid: linux-arm64}
          - {target: web-wasm, src: liblzo2.a, dst: liblzo2.a, rid: browser-wasm}
    
    container:
      image: dockcross/${{ matrix.compiler.target }}

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract lzo-${{ env.LZO_VERSION }}
      run: | 
        wget https://www.oberhumer.com/opensource/lzo/download/lzo-${{ env.LZO_VERSION }}.tar.gz
        tar -xzvf lzo-${{ env.LZO_VERSION }}.tar.gz
    
    - name: Compile lzo-${{ env.LZO_VERSION }}
      run: |
        cmake -B build/${{ matrix.compiler.target }} -S lzo-${{ env.LZO_VERSION }}/ -G Ninja -DENABLE_STATIC=0 -DENABLE_SHARED=1
        ninja -C build/${{ matrix.compiler.target }} lzo_shared_lib
        mkdir -p runtimes/${{ matrix.compiler.rid }}/native
        cp build/${{ matrix.compiler.target }}/${{ matrix.compiler.src }} runtimes/${{ matrix.compiler.rid }}/native/${{ matrix.compiler.dst }}

    - name: Upload lzo-${{ env.LZO_VERSION }} artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lzo-${{ env.LZO_VERSION }}-${{ matrix.compiler.target }}
        path: runtimes