name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Pack
        run: |
          dotnet pack -c Release
      - name: Push package
        run: |
          find src/SharpLzo/bin/Release -name '*.nupkg' | xargs -i dotnet nuget push {} -k ${{ secrets.NUGET_API_KEY }} -s https://www.myget.org/F/wtfblub/api/v2/package
